name: Publish (release)
on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: 'Release type'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  test:
    name: Print github ref
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: echo ${{ github.ref }}
  publish:
    name: Publish to package registry
    runs-on: ubuntu-latest
    if: github.ref == 'master'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Bump version
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          npm version ${{ github.event.inputs.releaseType }}
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish package
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}